gpu: "0"
multi_gpu: null

pc1: ./data/cat1/source.txt # dog3 person1 person2
pc2: ./data/cat1/target.txt # dog3 person1 person2

model_name: SuperGlue

full: False
fast_test: False

evaluate: True
resume: True
ckpt_dir: ./pretrained/rmanet/

# general args
batch_size: 1
pretrain: nonrigidsupervised.pth # nonrigidself.pth
num_points: 2048

DEVICE: cuda

dataset: RMANet

# miscalleneous
workers: 1

BCPD:
  LMBD: 2
  BETA: 2 # 0.5
  GAMMA: 3
  K: 100

# GM model parameters
GM:
  FEATURE_CHANNEL: 256
  OT_ITER_NUM: 20
  PROJ_FEAT: 256
  NEIGHBORSNUM: 20
  ATTEND: attentiontransformer
  NATTEND: 4
  ALPHASCORE: False
  SKADDCR: True

DATASET:
  NOISE_TYPE: crop  #clean, outlier, holes, crop
  UNSEEN: False
  ROT_MAG: 0.0
  SCALE_MAG: 1.0
  TRANS_MAG: 0.0
  PARTIAL_P_KEEP:
    - 1.0
    - 0.7
  NHOLES: 20
  KHOLES: 25

EVAL:
  CYCLE: False
  LOOP: False



